### ISSUE TITLE
Programming of ESP-12E

### ISSUE THREAD

**Issue by repetto74** [JanDerogee/SerialSpeechSynthesizerSAM#1]
Hi,

I am willing to build this very interesting project :-). 
Just one question concerning the programming of the ESP-12E. Can this be done straight with the ESP-12E soldered on the PCB and through the 5 pins header? I am willing to use a USB to Serial programmer but as far as I understood, I will need to provide a +5v input to the PCB as the Serial programmer will not be able to provide enough power. 
Is that correct?
Many thanks in advance :-)
Rick

**Comment by JanDerogee** [comment]
Hello Rick,
all the information you seek is located in the user manual page 53 and further. Please also refer to the schematic for more details.
You do need to apply 5V to the PCB via the other connector! The 5-pin header only carries 3.3V out and is not an input! This device was designed to be connected to a CBM computer that supplies the 5V and the 5-pin header is intended to be connected to a RS-232 to TTL converter (or USB). If your converter supplies power... do not connect it to the 5-pin header.

Jan

________________________________
From: repetto74 ***@***.***>
Sent: Saturday, September 30, 2023 8:04 PM
To: JanDerogee/SerialSpeechSynthesizerSAM ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [JanDerogee/SerialSpeechSynthesizerSAM] Programming of ESP-12E (Issue #1)


Hi,

I am willing to build this very interesting project :-).
Just one question concerning the programming of the ESP-12E. Can this be done straight with the ESP-12E soldered on the PCB and through the 5 pins header? I am willing to use a USB to Serial programmer but as far as I understood, I will need to provide a +5v input to the PCB as the Serial programmer will not be able to provide enough power.
Is that correct?
Many thanks in advance :-)
Rick

**Comment by repetto74** [comment]
Hello Jan,

Ok thanks now that looks more clear to me :-).
My USB to TTL adapter can indeed output 3.3V but understood that the 3.3v on the 5 pins header is an output and therefore I should NOT connect the 3.3v pin of the USB to TTL converter!
I will connect then RXD, TXD and GND between the 5 pin header and the TTL converter.
I will supply the required +3.3V by either inserting the SAM cart in the VIC20 user port or supply externally a +5v DC to the pin headers marked +5v and GND.
Many thanks for the clarifications :-)!
Rick

**Comment by JanDerogee** [comment]
That's the way to do it, have fun.
Jan
________________________________

**Comment by repetto74** [comment]
Hello Jan,

I am struggling a little to have the compile working with the Arduino IDE before programming the ESP-12E. I have installed all the required libraries but compiling is still failing.
I noticed that there is a .bin file already available in your Github repository and would like to program it straight in the ESP-12E.
Any suggestion on what tool I may use to upload this firmware using a USB Serial to TTL converter?
Many thanks.
Rick

**Comment by JanDerogee** [comment]
Hello Rick,
the bin file is only useful if you have an ESP that already contains the appropriate bootloader. Meaning that the .BIN file is intended for people to upgrade their existing device with the latest firmware.
I'm not aware of any other tool that allows you to upload the .BIN file into your ESP. I'm sure that they must exist (after all the arduino IDE is calling such a tool) but I have no experience with those at all. So I can't give you any advice about uploading the .BIN and if it will work at all.

If compilation is failing, what is the error message it generates?
Compilation should go well as long as you make sure that the following requirements are met:

I've build using core 2.7.4, JSON version 6

And with the arduino IDE settings (Tools) set to:
    board: ESP 12E
    uploadspeed: 115200
    CPU freq.: 160MHz
    flash size: 4M (1M SPIFFS)
    Debug port: disabled              \___ disabled and noassert saves both RAM and flash and prevent annoying messages from the core
    Debug level: NoAssert-NDEBUG      /
    IwIp: v2 lower memory
    Vtables: flash
    Exceptions: disabled
    Erase flash: only sketch

Kind regards, Jan
________________________________

**Comment by repetto74** [comment]
Hello Jan,

I was trying to compile and program with the Arduino IDE on my MacOSX. I tried again to set up all libraries in the Arduino IDE on my Windows partition and....success!! It compiled nicely and programmed the ESP-12E :-). All is working flawlessly!
Thanks this is a super piece of hardware for the VIC20 :-D. Still have to go through the manual and understand what settings can be changed.

https://github.com/JanDerogee/SerialSpeechSynthesizerSAM/assets/69641967/107be71a-750b-4521-85a3-b8f9942acb26


https://github.com/JanDerogee/SerialSpeechSynthesizerSAM/assets/69641967/ba34fd03-b322-45ca-ba3b-fae0faa573a7


![IMG_5737](https://github.com/JanDerogee/SerialSpeechSynthesizerSAM/assets/69641967/75c9d468-d9c2-4758-b2b4-8123127f5fa2)

**Comment by JanDerogee** [comment]
Cool to hear it works now. Thanks for letting me know.
Have fun with the project.
Kind regards, Jan.

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________
